from date_dimension import DateDimension
from datetime import date
import pytest

class TestDateTime():
    @pytest.mark.parametrize("year,month,day,expected", [
        (2024, 12, 25, {
                "iso_week_date": "202452.3",
                "day": 25,
                "day_abbreviation": "Wed",
                "day_name": "Wednesday",
                "day_of_quarter": 86,
                "day_of_semester": 178,
                "day_of_trimester": 116,
                "day_of_week": 3,
                "day_of_year": 360,
                "first_day_of_quarter": date(2024, 10, 1),
                "first_day_of_semester": date(2024, 7, 1),
                "first_day_of_trimester": date(2024, 9, 1),
                "holiday": "Christmas Day",
                "is_holiday": True,
                "is_weekend": False,
                "isodate": date(2024, 12, 25),
                "key": 20241225,
                "last_day_of_quarter": date(2024, 12, 31),
                "last_day_of_semester": date(2024, 12, 31),
                "last_day_of_trimester": date(2024, 12, 31),
                "leap_year": True,
                "month": 12,
                "month_abbreviation": "Dec",
                "month_id": "2024M12",
                "month_name": "December",
                "quarter": 4,
                "quarter_id": "2024Q4",
                "season": "Winter",
                "semester": 2,
                "semester_id": "2024S2",
                "trimester": 3,
                "trimester_id": "2024T3",
                "week": 52,
                "week_id": "2024W52",
                "year": 2024
            }),
        (1978, 6, 30, {
                "iso_week_date": "197826.5",
                "day": 30,
                "day_abbreviation": "Fri",
                "day_name": "Friday",
                "day_of_quarter": 91,
                "day_of_semester": 181,
                "day_of_trimester": 61,
                "day_of_week": 5,
                "day_of_year": 181,
                "first_day_of_quarter": date(1978, 4, 1),
                "first_day_of_semester": date(1978, 1, 1),
                "first_day_of_trimester": date(1978, 5, 1),
                "holiday": None,
                "is_holiday": False,
                "is_weekend": False,
                "isodate": date(1978, 6, 30),
                "key": 19780630,
                "last_day_of_quarter": date(1978, 6, 30),
                "last_day_of_semester": date(1978, 6, 30),
                "last_day_of_trimester": date(1978, 8, 31),
                "leap_year": False,
                "month": 6,
                "month_abbreviation": "Jun",
                "month_id": "1978M06",
                "month_name": "June",
                "quarter": 2,
                "quarter_id": "1978Q2",
                "semester": 1,
                "semester_id": "1978S1",
                "season": "Summer",
                "trimester": 2,
                "trimester_id": "1978T2",
                "week": 26,
                "week_id": "1978W26",
                "year": 1978
            }),
        (2012, 3, 24, {
                "iso_week_date": "201212.6",
                "day": 24,
                "day_abbreviation": "Sat",
                "day_name": "Saturday",
                "day_of_quarter": 84,
                "day_of_semester": 84,
                "day_of_trimester": 84,
                "day_of_week": 6,
                "day_of_year": 84,
                "first_day_of_quarter": date(2012, 1, 1),
                "first_day_of_semester": date(2012, 1, 1),
                "first_day_of_trimester": date(2012, 1, 1),
                "holiday": None,
                "is_holiday": False,
                "is_weekend": True,
                "isodate": date(2012, 3, 24),
                "key": 20120324,
                "last_day_of_quarter": date(2012, 3, 31),
                "last_day_of_semester": date(2012, 6, 30),
                "last_day_of_trimester": date(2012, 4, 30),
                "leap_year": True,
                "month": 3,
                "month_abbreviation": "Mar",
                "month_id": "2012M03",
                "month_name": "March",
                "quarter": 1,
                "quarter_id": "2012Q1",
                "semester": 1,
                "semester_id": "2012S1",
                "season": "Spring",
                "trimester": 1,
                "trimester_id": "2012T1",
                "week": 12,
                "week_id": "2012W12",
                "year": 2012
            }),
        (1996, 2, 29, {
                "iso_week_date": "199609.4",
                "day": 29,
                "day_abbreviation": "Thu",
                "day_name": "Thursday",
                "day_of_quarter": 60,
                "day_of_semester": 60,
                "day_of_trimester": 60,
                "day_of_week": 4,
                "day_of_year": 60,
                "first_day_of_quarter": date(1996, 1, 1),
                "first_day_of_semester": date(1996, 1, 1),
                "first_day_of_trimester": date(1996, 1, 1),
                "holiday": None,
                "is_holiday": False,
                "is_weekend": False,
                "isodate": date(1996, 2, 29),
                "key": 19960229,
                "last_day_of_quarter": date(1996, 3, 31),
                "last_day_of_semester": date(1996, 6, 30),
                "last_day_of_trimester": date(1996, 4, 30),
                "leap_year": True,
                "month": 2,
                "month_abbreviation": "Feb",
                "month_id": "1996M02",
                "month_name": "February",
                "quarter": 1,
                "quarter_id": "1996Q1",
                "semester": 1,
                "semester_id": "1996S1",
                "season": "Winter",
                "trimester": 1,
                "trimester_id": "1996T1",
                "week": 9,
                "week_id": "1996W09",
                "year": 1996
            }),
        (2008, 1, 1, {
                "iso_week_date": "200801.2",
                "day": 1,
                "day_abbreviation": "Tue",
                "day_name": "Tuesday",
                "day_of_quarter": 1,
                "day_of_semester": 1,
                "day_of_trimester": 1,
                "day_of_week": 2,
                "day_of_year": 1,
                "first_day_of_quarter": date(2008, 1, 1),
                "first_day_of_semester": date(2008, 1, 1),
                "first_day_of_trimester": date(2008, 1, 1),
                "holiday": "New Year's Day",
                "is_holiday": True,
                "is_weekend": False,
                "isodate": date(2008, 1, 1),
                "key": 20080101,
                "last_day_of_quarter": date(2008, 3, 31),
                "last_day_of_semester": date(2008, 6, 30),
                "last_day_of_trimester": date(2008, 4, 30),
                "leap_year": True,
                "month": 1,
                "month_abbreviation": "Jan",
                "month_id": "2008M01",
                "month_name": "January",
                "quarter": 1,
                "quarter_id": "2008Q1",
                "semester": 1,
                "semester_id": "2008S1",
                "season": "Winter",
                "trimester": 1,
                "trimester_id": "2008T1",
                "week": 1,
                "week_id": "2008W01",
                "year": 2008
            }),
        (2010, 1, 1, {
                "iso_week_date": "200953.5",
                "day": 1,
                "day_abbreviation": "Fri",
                "day_name": "Friday",
                "day_of_quarter": 1,
                "day_of_semester": 1,
                "day_of_trimester": 1,
                "day_of_week": 5,
                "day_of_year": 1,
                "first_day_of_quarter": date(2010, 1, 1),
                "first_day_of_semester": date(2010, 1, 1),
                "first_day_of_trimester": date(2010, 1, 1),
                "holiday": "New Year's Day",
                "is_holiday": True,
                "is_weekend": False,
                "isodate": date(2010, 1, 1),
                "key": 20100101,
                "last_day_of_quarter": date(2010, 3, 31),
                "last_day_of_semester": date(2010, 6, 30),
                "last_day_of_trimester": date(2010, 4, 30),
                "leap_year": False,
                "month": 1,
                "month_abbreviation": "Jan",
                "month_id": "2010M01",
                "month_name": "January",
                "quarter": 1,
                "quarter_id": "2010Q1",
                "semester": 1,
                "semester_id": "2010S1",
                "season": "Winter",
                "trimester": 1,
                "trimester_id": "2010T1",
                "week": 53,
                "week_id": "2009W53",
                "year": 2010
            })
    ])
    def test_pass(self, year, month, day, expected):
        d = DateDimension(date(year=year, month=month, day=day))
        assert {k: getattr(d, k) for k in dir(d) if isinstance(getattr(d.__class__, k, None), property)} == expected

